version: '3'

services:
  nginx:
    image: nginx:latest
    container_name: js_test

    ports:
      - "8080:80"
    volumes:
      - ./web:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    